defmodule DrivewayOSWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :driveway_os

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `:domain` is scoped to the parent host so the same session
  # carries across `admin.<host>`, `<tenant>.<host>`, and the bare
  # `<host>` — load-bearing for platform-admin impersonation, which
  # writes a customer_token on `admin.<host>` and redirects to
  # `<slug>.<host>`. Without the leading-dot domain, that cookie
  # would not be sent to the tenant subdomain and the operator
  # would land on a sign-in page instead of the impersonated
  # admin dashboard.
  @session_options [
    store: :cookie,
    key: "_driveway_os_key",
    signing_salt: "GKP6qHMT",
    same_site: "Lax",
    domain:
      Application.compile_env(:driveway_os, :session_cookie_domain) ||
        ".lvh.me"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :driveway_os,
    gzip: not code_reloading?,
    only: DrivewayOSWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :driveway_os
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # In test, allow Wallaby's ChromeDriver-driven session to share
  # the test process's SQL sandbox via a metadata header. No-op in
  # other environments.
  if Application.compile_env(:driveway_os, :sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox, sandbox: Application.compile_env(:driveway_os, :sandbox)
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Stripe webhook signature verification needs the raw request
    # body. Stash it on the conn so the webhook controller can read
    # it after the JSON parser has consumed it.
    body_reader: {DrivewayOSWeb.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DrivewayOSWeb.Router
end
