defmodule DrivewayOS.Accounts.Customer do
  @moduledoc """
  Tenant-scoped end customer. Books washes from the tenant they belong
  to (one Customer row per (tenant, person) — the same human signing
  in to two DrivewayOS-powered shops gets two separate rows).

  V1 Slice 2A: password authentication only. Slice 2C adds Google,
  Apple, and Facebook OAuth strategies as additional `strategies do
  … end` entries. Sign-in flow always happens in a tenant context
  (the `LoadTenant` plug sets it from the subdomain before the
  AshAuthentication action runs).
  """
  use Ash.Resource,
    otp_app: :driveway_os,
    domain: DrivewayOS.Accounts,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAuthentication],
    authorizers: [Ash.Policy.Authorizer]

  require Ash.Query

  @type t :: %__MODULE__{}

  postgres do
    table "customers"
    repo DrivewayOS.Repo
  end

  multitenancy do
    strategy :attribute
    attribute :tenant_id
    global? false
  end

  authentication do
    tokens do
      enabled? true
      token_resource DrivewayOS.Accounts.Token
      require_token_presence_for_authentication? true
      token_lifetime {7, :days}

      signing_secret DrivewayOS.Secrets
    end

    strategies do
      password :password do
        identity_field :email
        hashed_password_field :hashed_password

        register_action_accept [:name, :phone]

        # Forgot-password flow: AshAuth generates the
        # `request_password_reset_with_password` action + a
        # `password_reset_with_token_with_password` change. The
        # sender below receives (user, token, opts) and emails the
        # tenant-aware reset link.
        resettable do
          sender DrivewayOS.Accounts.PasswordResetSender
        end
      end

      # Built-in Google strategy. Credentials sourced from
      # GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET; redirect URI built
      # from `:oauth_redirect_base`. When env vars are missing, the
      # strategy is configured but inert — the redirect endpoint
      # 500s, but the app boots cleanly.
      google do
        client_id DrivewayOS.Secrets
        client_secret DrivewayOS.Secrets
        redirect_uri DrivewayOS.Secrets
      end

      # Generic OAuth2 strategy for Facebook. Pre-filled with FB's
      # endpoints so only credentials need configuring.
      oauth2 :facebook do
        client_id DrivewayOS.Secrets
        client_secret DrivewayOS.Secrets
        redirect_uri DrivewayOS.Secrets
        base_url "https://graph.facebook.com"
        authorize_url "https://www.facebook.com/v18.0/dialog/oauth"
        token_url "https://graph.facebook.com/v18.0/oauth/access_token"
        user_url "https://graph.facebook.com/v18.0/me?fields=id,name,email"
        auth_method :client_secret_post
      end

      # Sign in with Apple — uses a JWT-based client_secret minted
      # from team_id + private_key_id + private_key (P8 file).
      apple do
        client_id DrivewayOS.Secrets
        team_id DrivewayOS.Secrets
        private_key_id DrivewayOS.Secrets
        private_key_path DrivewayOS.Secrets
        redirect_uri DrivewayOS.Secrets
      end
    end
  end

  policies do
    # Authentication actions short-circuit before actor-based policies.
    # No actor is set during sign-in/registration; the multitenancy
    # filter still runs (because every action requires `tenant:`),
    # so isolation is preserved.
    bypass action(:register_with_password) do
      authorize_if always()
    end

    bypass action(:sign_in_with_password) do
      authorize_if always()
    end

    bypass action(:sign_in_with_token) do
      authorize_if always()
    end

    bypass action(:get_by_subject) do
      authorize_if always()
    end

    # Forgot-password actions generated by `resettable do … end`.
    # Both run unauthenticated by design — the security model is
    # "you proved access to the email inbox, that's the auth."
    bypass action(:request_password_reset_with_password) do
      authorize_if always()
    end

    bypass action(:password_reset_with_password) do
      authorize_if always()
    end

    # Customers can read/update themselves; admins (tenant-scoped) can
    # read/update any customer in their tenant. Cross-tenant reads are
    # impossible because multitenancy filters them out at the query
    # layer.
    policy action_type(:read) do
      authorize_if expr(id == ^actor(:id))
      authorize_if expr(^actor(:role) == :admin)
    end

    policy action_type(:update) do
      authorize_if expr(id == ^actor(:id))
      authorize_if expr(^actor(:role) == :admin)
    end

    policy action_type(:destroy) do
      authorize_if expr(^actor(:role) == :admin)
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :tenant_id, :uuid do
      allow_nil? false
      public? true
    end

    attribute :email, :ci_string do
      allow_nil? false
      public? true
    end

    attribute :name, :string do
      allow_nil? false
      public? true
      constraints min_length: 1, max_length: 100
    end

    attribute :phone, :string do
      public? true
      constraints max_length: 30
    end

    attribute :role, :atom do
      constraints one_of: [:customer, :technician, :admin, :guest]
      default :customer
      allow_nil? false
      public? true
    end

    attribute :hashed_password, :string do
      allow_nil? true
      sensitive? true
    end

    # Nil until the user verifies. Soft-gate: unverified accounts are
    # nudged via banner but not blocked from booking, paying, etc.
    attribute :email_verified_at, :utc_datetime_usec do
      public? true
    end

    # Free-text admin notes about this customer (gate code, vehicle
    # quirks, "always wants the deluxe wax", etc.). Visible only to
    # tenant admins. V2 splits into a CustomerNote resource if we
    # need timestamped, multi-author entries.
    attribute :admin_notes, :string do
      public? true
      constraints max_length: 5000
    end

    # Guest customers — created via the booking wizard's "continue
    # as guest" path when the tenant has :guest_checkout enabled.
    # They have no password (so can't sign in via /sign-in directly)
    # but DO have email/name so we can email them the confirmation.
    # The future "claim your account" flow promotes them to full
    # password-auth customers.
    attribute :guest?, :boolean do
      default false
      allow_nil? false
      public? true
    end

    # Loyalty punch card progress. Increments by 1 each time an
    # Appointment for this customer transitions to :completed
    # (UNLESS that appointment was itself a loyalty redemption —
    # see Phase J3). Resets to 0 when a redemption is created so
    # the punch card cycles cleanly.
    attribute :loyalty_count, :integer do
      default 0
      allow_nil? false
      public? true
      constraints min: 0
    end

    # Marketing-comms opt-out. Operational emails (booking
    # confirmation / reminder / status changes / cancellation /
    # payment-failed / account-deleted) ALWAYS send — they're
    # transactional and customers expect them. This flag gates
    # things like the "you earned a free wash" loyalty email +
    # any future re-engagement campaigns. Default `true` so
    # existing customers keep getting the loyalty perk; the
    # opt-out is on the customer's profile.
    attribute :marketing_emails_ok?, :boolean do
      default true
      allow_nil? false
      public? true
    end

    # GDPR-style anonymization timestamp. Customer hits "Delete
    # my account" on /me; we set this + scrub identifying fields
    # rather than DELETE the row outright (keeping the row
    # preserves FK integrity for the tenant's appointment history,
    # which they often need for accounting/audit). The scrubbed
    # row's email is `deleted-<uuid>@deleted.invalid` so unique-
    # email constraints don't conflict if the same person
    # re-registers later.
    attribute :deleted_at, :utc_datetime_usec do
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  identities do
    # Email uniqueness is automatically scoped by tenant_id thanks to
    # the multitenancy block above — same email can register on two
    # different tenants without colliding.
    identity :unique_email, [:email]
  end

  validations do
    # Mirrors PlatformUser's password rules. Will be extracted into a
    # shared `DrivewayOS.Accounts.Validations.Password` if a third
    # caller appears.
    validate(
      fn changeset, _ctx ->
        case Ash.Changeset.get_argument(changeset, :password) do
          nil ->
            :ok

          password when is_binary(password) ->
            cond do
              String.length(password) < 10 ->
                {:error, field: :password, message: "must be at least 10 characters"}

              not String.match?(password, ~r/[A-Z]/) ->
                {:error, field: :password, message: "must contain at least one uppercase letter"}

              not String.match?(password, ~r/[a-z]/) ->
                {:error, field: :password, message: "must contain at least one lowercase letter"}

              not String.match?(password, ~r/[0-9]/) ->
                {:error, field: :password, message: "must contain at least one number"}

              true ->
                :ok
            end

          _ ->
            :ok
        end
      end,
      on: [:create]
    )

    # Reject obvious email garbage. Permissive enough to allow normal
    # addresses, strict enough to catch input like "haha" or
    # "@example.com" before AshAuthentication tries to mail it.
    validate fn changeset, _ctx ->
      case Ash.Changeset.get_attribute(changeset, :email) do
        nil -> :ok
        %Ash.CiString{} = ci -> validate_email_format(to_string(ci))
        email when is_binary(email) -> validate_email_format(email)
        _ -> :ok
      end
    end
  end

  actions do
    defaults [:read, update: :*]

    update :verify_email do
      # Inherits the resource's anonymous validators, which aren't
      # atomic-aware. The action runs over a single row in a tiny
      # transaction so non-atomic is fine.
      require_atomic? false
      change set_attribute(:email_verified_at, &DateTime.utc_now/0)
    end

    update :increment_loyalty do
      require_atomic? false

      change fn changeset, _ ->
        current = changeset.data.loyalty_count || 0
        Ash.Changeset.force_change_attribute(changeset, :loyalty_count, current + 1)
      end
    end

    update :reset_loyalty do
      require_atomic? false
      change set_attribute(:loyalty_count, 0)
    end

    update :anonymize do
      # Scrub identifying fields. Email gets a deterministic
      # synthetic address per row (preserves uniqueness +
      # signals to operators that the row is anonymized).
      # hashed_password going nil locks both password + magic-
      # link sign-in for this row — magic-link would also fail
      # the email lookup since the new email is synthetic.
      require_atomic? false

      change fn changeset, _ctx ->
        synthetic_email = "deleted-#{changeset.data.id}@deleted.invalid"

        changeset
        |> Ash.Changeset.force_change_attribute(:email, synthetic_email)
        |> Ash.Changeset.force_change_attribute(:name, "Deleted customer")
        |> Ash.Changeset.force_change_attribute(:phone, nil)
        |> Ash.Changeset.force_change_attribute(:hashed_password, nil)
        |> Ash.Changeset.force_change_attribute(:admin_notes, nil)
        |> Ash.Changeset.force_change_attribute(:deleted_at, DateTime.utc_now())
      end
    end

    create :register_guest do
      # Booking-wizard guest checkout. No password (can't sign in
      # via /sign-in until the customer claims the account). Upserts
      # by email — if a real customer with this email already
      # exists in this tenant, just return them; otherwise create a
      # fresh guest row.
      accept [:email, :name, :phone]

      upsert? true
      upsert_identity :unique_email

      change set_attribute(:guest?, true)
      change set_attribute(:role, :customer)
    end

    create :register_with_google do
      argument :user_info, :map, allow_nil?: false
      argument :oauth_tokens, :map, allow_nil?: false

      upsert? true
      upsert_identity :unique_email
      upsert_fields []

      change set_attribute(:role, :customer)
      change DrivewayOS.Accounts.Changes.SetCustomerFromOAuth
      change AshAuthentication.GenerateTokenChange
    end

    create :register_with_facebook do
      argument :user_info, :map, allow_nil?: false
      argument :oauth_tokens, :map, allow_nil?: false

      upsert? true
      upsert_identity :unique_email
      upsert_fields []

      change set_attribute(:role, :customer)
      change DrivewayOS.Accounts.Changes.SetCustomerFromOAuth
      change AshAuthentication.GenerateTokenChange
    end

    create :register_with_apple do
      argument :user_info, :map, allow_nil?: false
      argument :oauth_tokens, :map, allow_nil?: false

      upsert? true
      upsert_identity :unique_email
      upsert_fields []

      change set_attribute(:role, :customer)
      change DrivewayOS.Accounts.Changes.SetCustomerFromOAuth
      change AshAuthentication.GenerateTokenChange
    end
  end

  defp validate_email_format(email) do
    if String.match?(email, ~r/^[^\s@]+@[^\s@]+\.[^\s@]+$/) do
      :ok
    else
      {:error, field: :email, message: "must be a valid email address"}
    end
  end
end
