import Config

# Configure your database
config :driveway_os, DrivewayOS.Repo,
  username: System.get_env("DB_USER", "wrich"),
  password: System.get_env("DB_PASS", ""),
  hostname: "localhost",
  database: "driveway_os_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :driveway_os, DrivewayOSWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "V28L1g1dQuswS5PFykFhlVv7Ermv00sW1zhRwSE0Zj2pO/0O2N01gQCyj4/Tf8Lc",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:driveway_os, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:driveway_os, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :driveway_os, DrivewayOSWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/driveway_os_web/router\.ex$",
      ~r"lib/driveway_os_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :driveway_os, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Platform-tier (DrivewayOS operator) token signing secret. Separate
# from the customer token secret so rotating one population doesn't
# invalidate the other.
config :driveway_os,
       :platform_token_signing_secret,
       System.get_env("PLATFORM_TOKEN_SIGNING_SECRET") ||
         "dev-only-platform-secret-change-in-production-at-least-64-chars"

# Local subdomain routing — `*.lvh.me` resolves to 127.0.0.1 in public
# DNS, so no `/etc/hosts` edits needed. `acme.lvh.me:4000` → tenant
# "acme", `lvh.me:4000` → marketing, `admin.lvh.me:4000` → platform admin.
config :driveway_os, :platform_host, System.get_env("PLATFORM_HOST") || "lvh.me"
