import Config

# Session cookie domain — see config/dev.exs for the rationale.
# Production reads PLATFORM_HOST from env and prefixes a leading
# dot at compile time. If PLATFORM_HOST isn't set at compile-time,
# this falls back to drivewayos.com (the canonical SaaS host).
config :driveway_os,
       :session_cookie_domain,
       "." <> (System.get_env("PLATFORM_HOST") || "drivewayos.com")

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :driveway_os, DrivewayOSWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :driveway_os, DrivewayOSWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
