defmodule DrivewayOS.Repo.Migrations.AddAppointmentIsLoyaltyRedemption do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :is_loyalty_redemption, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:appointments) do
      remove :is_loyalty_redemption
    end
  end
end
