defmodule DrivewayOS.Repo.Migrations.AddAppointmentPhotos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointment_photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :kind, :text, null: false, default: "pre_booking"
      add :storage_path, :text, null: false
      add :content_type, :text, null: false
      add :byte_size, :bigint, null: false
      add :caption, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "appointment_photos_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "appointment_photos_appointment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointment_photos, "appointment_photos_customer_id_fkey")

    drop constraint(:appointment_photos, "appointment_photos_appointment_id_fkey")

    drop table(:appointment_photos)
  end
end
