defmodule DrivewayOS.Repo.Migrations.AddSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :frequency, :text, null: false
      add :status, :text, null: false, default: "active"
      add :starts_at, :utc_datetime_usec, null: false
      add :next_run_at, :utc_datetime_usec, null: false
      add :last_run_at, :utc_datetime_usec
      add :vehicle_description, :text, null: false
      add :service_address, :text, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "subscriptions_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "subscriptions_service_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :vehicle_id,
          references(:vehicles,
            column: :id,
            name: "subscriptions_vehicle_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :address_id,
          references(:addresses,
            column: :id,
            name: "subscriptions_address_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:subscriptions, "subscriptions_customer_id_fkey")

    drop constraint(:subscriptions, "subscriptions_service_type_id_fkey")

    drop constraint(:subscriptions, "subscriptions_vehicle_id_fkey")

    drop constraint(:subscriptions, "subscriptions_address_id_fkey")

    drop table(:subscriptions)
  end
end
