defmodule DrivewayOS.Repo.Migrations.CreatePlatformTenantReferrals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_tenant_referrals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :event_type, :text, null: false
      add :metadata, :map, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "platform_tenant_referrals_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:platform_tenant_referrals, [:provider, :event_type, :occurred_at])

    create index(:platform_tenant_referrals, [:tenant_id, :provider])
  end

  def down do
    drop constraint(:platform_tenant_referrals, "platform_tenant_referrals_tenant_id_fkey")

    drop_if_exists index(:platform_tenant_referrals, [:tenant_id, :provider])

    drop_if_exists index(:platform_tenant_referrals, [:provider, :event_type, :occurred_at])

    drop table(:platform_tenant_referrals)
  end
end
