defmodule DrivewayOS.Repo.Migrations.AddOperatorNotesToAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :operator_notes, :text
    end
  end

  def down do
    alter table(:appointments) do
      remove :operator_notes
    end
  end
end
