defmodule DrivewayOS.Repo.Migrations.AddCustomDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_custom_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :hostname, :text, null: false
      add :verification_token, :text, null: false
      add :verified_at, :utc_datetime_usec
      add :ssl_status, :text, null: false, default: "none"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "platform_custom_domains_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:platform_custom_domains, [:hostname],
             name: "platform_custom_domains_unique_hostname_index"
           )
  end

  def down do
    drop constraint(:platform_custom_domains, "platform_custom_domains_tenant_id_fkey")

    drop_if_exists unique_index(:platform_custom_domains, [:hostname],
                     name: "platform_custom_domains_unique_hostname_index"
                   )

    drop table(:platform_custom_domains)
  end
end
