defmodule DrivewayOS.Repo.Migrations.LinkAppointmentToVehicleAndAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :vehicle_id,
          references(:vehicles,
            column: :id,
            name: "appointments_vehicle_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :address_id,
          references(:addresses,
            column: :id,
            name: "appointments_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:appointments, "appointments_vehicle_id_fkey")

    drop constraint(:appointments, "appointments_address_id_fkey")

    alter table(:appointments) do
      remove :address_id
      remove :vehicle_id
    end
  end
end
