defmodule DrivewayOS.Repo.Migrations.AddOauthStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_oauth_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :purpose, :text, null: false, default: "stripe_connect"
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "platform_oauth_states_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:platform_oauth_states, [:token],
             name: "platform_oauth_states_unique_token_index"
           )
  end

  def down do
    drop constraint(:platform_oauth_states, "platform_oauth_states_tenant_id_fkey")

    drop_if_exists unique_index(:platform_oauth_states, [:token],
                     name: "platform_oauth_states_unique_token_index"
                   )

    drop table(:platform_oauth_states)
  end
end
