defmodule DrivewayOS.Repo.Migrations.AdditionalVehiclesToMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Postgres can't auto-cast text[] to jsonb[] and can't use a
  # subquery in a USING transform. Multi-vehicle only shipped a day
  # ago and there's no live production data, so we drop + re-add
  # the column rather than write a PL/pgSQL function for the
  # conversion. Any test/staging rows had empty arrays anyway.
  def up do
    alter table(:appointments) do
      remove :additional_vehicles
      add :additional_vehicles, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:appointments) do
      remove :additional_vehicles
      add :additional_vehicles, {:array, :string}, default: []
    end
  end
end
