defmodule DrivewayOS.Repo.Migrations.AddTenantLastDigestSentAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :last_digest_sent_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:tenants) do
      remove :last_digest_sent_at
    end
  end
end
