defmodule DrivewayOS.Repo.Migrations.Slice2aCustomerPasswordAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :email, :citext, null: false
      add :name, :text, null: false
      add :phone, :text
      add :role, :text, null: false, default: "customer"
      add :hashed_password, :text
      add :email_verified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:tenant_id, :email], name: "customers_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:customers, [:tenant_id, :email],
                     name: "customers_unique_email_index"
                   )

    drop table(:customers)

    drop table(:tokens)
  end
end
