defmodule DrivewayOS.Repo.Migrations.AddBookingDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:booking_drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :step, :text, null: false
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "booking_drafts_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:booking_drafts, [:tenant_id, :customer_id],
             name: "booking_drafts_unique_per_customer_index"
           )
  end

  def down do
    drop constraint(:booking_drafts, "booking_drafts_customer_id_fkey")

    drop_if_exists unique_index(:booking_drafts, [:tenant_id, :customer_id],
                     name: "booking_drafts_unique_per_customer_index"
                   )

    drop table(:booking_drafts)
  end
end
