defmodule DrivewayOS.Repo.Migrations.AddPaymentFieldsToAppointment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :stripe_checkout_session_id, :text
      add :stripe_payment_intent_id, :text
      add :payment_status, :text, null: false, default: "unpaid"
      add :paid_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:appointments) do
      remove :paid_at
      remove :payment_status
      remove :stripe_payment_intent_id
      remove :stripe_checkout_session_id
    end
  end
end
