defmodule DrivewayOS.Repo.Migrations.AddAddresses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :street_line1, :text, null: false
      add :street_line2, :text
      add :city, :text, null: false
      add :state, :text, null: false
      add :zip, :text, null: false
      add :lat, :float
      add :lon, :float
      add :nickname, :text
      add :instructions, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "addresses_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:addresses, "addresses_customer_id_fkey")

    drop table(:addresses)
  end
end
