defmodule DrivewayOS.Repo.Migrations.Slice5ServiceTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:service_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :base_price_cents, :bigint, null: false
      add :duration_minutes, :bigint, null: false
      add :active, :boolean, null: false, default: true
      add :stripe_product_id, :text
      add :stripe_price_id, :text
      add :sort_order, :bigint, null: false, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:service_types, [:tenant_id, :slug],
             name: "service_types_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:service_types, [:tenant_id, :slug],
                     name: "service_types_unique_slug_index"
                   )

    drop table(:service_types)
  end
end
