defmodule DrivewayOS.Repo.Migrations.AddPlatformPlans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tier, :text, null: false
      add :name, :text, null: false
      add :monthly_cents, :bigint, null: false, default: 0
      add :blurb, :text
      add :features, {:array, :text}, null: false, default: []
      add :limit_services, :bigint, default: -1
      add :limit_block_templates, :bigint, default: -1
      add :limit_bookings_per_month, :bigint, default: -1
      add :limit_technicians, :bigint, default: -1
      add :sort_order, :bigint, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:platform_plans, [:tier], name: "platform_plans_unique_tier_index")
  end

  def down do
    drop_if_exists unique_index(:platform_plans, [:tier],
                     name: "platform_plans_unique_tier_index"
                   )

    drop table(:platform_plans)
  end
end
