defmodule DrivewayOS.Repo.Migrations.CreatePlatformEmailConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_email_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :external_key_id, :text
      add :api_key, :text
      add :auto_send_enabled, :boolean, null: false, default: true
      add :connected_at, :utc_datetime_usec
      add :disconnected_at, :utc_datetime_usec
      add :last_send_at, :utc_datetime_usec
      add :last_send_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "platform_email_connections_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:platform_email_connections, [:tenant_id, :provider],
             name: "platform_email_connections_unique_tenant_provider_index"
           )
  end

  def down do
    drop constraint(:platform_email_connections, "platform_email_connections_tenant_id_fkey")

    drop_if_exists unique_index(:platform_email_connections, [:tenant_id, :provider],
                     name: "platform_email_connections_unique_tenant_provider_index"
                   )

    drop table(:platform_email_connections)
  end
end
