defmodule DrivewayOS.Repo.Migrations.AddGuestToCustomer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :guest?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:customers) do
      remove :guest?
    end
  end
end
