defmodule DrivewayOS.Repo.Migrations.AddSquareOrderIdToAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :square_order_id, :text
    end
  end

  def down do
    alter table(:appointments) do
      remove :square_order_id
    end
  end
end
