defmodule DrivewayOS.Repo.Migrations.AddAuditLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_audit_log, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :target_type, :text
      add :target_id, :text
      add :payload, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "platform_audit_log_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :platform_user_id,
          references(:platform_users,
            column: :id,
            name: "platform_audit_log_platform_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:platform_audit_log, "platform_audit_log_tenant_id_fkey")

    drop constraint(:platform_audit_log, "platform_audit_log_platform_user_id_fkey")

    drop table(:platform_audit_log)
  end
end
