defmodule DrivewayOS.Repo.Migrations.AddWizardProgressAndPostmarkToTenants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :wizard_progress, :map, default: %{}
      add :postmark_server_id, :text
      add :postmark_api_key, :text
    end
  end

  def down do
    alter table(:tenants) do
      remove :postmark_api_key
      remove :postmark_server_id
      remove :wizard_progress
    end
  end
end
