defmodule DrivewayOS.Repo.Migrations.Slice1PlatformDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :citext, null: false
      add :display_name, :text, null: false
      add :legal_name, :text
      add :status, :text, null: false, default: "pending_onboarding"
      add :stripe_account_id, :text
      add :stripe_account_status, :text, null: false, default: "none"
      add :subdomain, :text
      add :primary_color_hex, :text
      add :logo_url, :text
      add :support_email, :text
      add :support_phone, :text
      add :timezone, :text, null: false, default: "America/Chicago"
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tenants, [:slug], name: "tenants_unique_slug_index")

    create unique_index(:tenants, [:stripe_account_id],
             name: "tenants_unique_stripe_account_id_index"
           )

    create unique_index(:tenants, [:subdomain], name: "tenants_unique_subdomain_index")

    create table(:tenant_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :plan_tier, :text, null: false, default: "starter"
      add :status, :text, null: false, default: "trialing"
      add :stripe_subscription_id, :text
      add :current_period_start, :date
      add :current_period_end, :date
      add :trial_ends_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "tenant_subscriptions_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:tenant_subscriptions, [:stripe_subscription_id],
             name: "tenant_subscriptions_unique_stripe_subscription_id_index"
           )

    create table(:platform_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
      add :role, :text, null: false, default: "support"
      add :hashed_password, :text
      add :email_verified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:platform_users, [:email], name: "platform_users_unique_email_index")

    create table(:platform_tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:platform_tokens)

    drop_if_exists unique_index(:platform_users, [:email],
                     name: "platform_users_unique_email_index"
                   )

    drop table(:platform_users)

    drop constraint(:tenant_subscriptions, "tenant_subscriptions_tenant_id_fkey")

    drop_if_exists unique_index(:tenant_subscriptions, [:stripe_subscription_id],
                     name: "tenant_subscriptions_unique_stripe_subscription_id_index"
                   )

    drop table(:tenant_subscriptions)

    drop_if_exists unique_index(:tenants, [:subdomain], name: "tenants_unique_subdomain_index")

    drop_if_exists unique_index(:tenants, [:stripe_account_id],
                     name: "tenants_unique_stripe_account_id_index"
                   )

    drop_if_exists unique_index(:tenants, [:slug], name: "tenants_unique_slug_index")

    drop table(:tenants)
  end
end
