defmodule DrivewayOS.Repo.Migrations.AddAdminNotesToCustomer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :admin_notes, :text
    end
  end

  def down do
    alter table(:customers) do
      remove :admin_notes
    end
  end
end
