defmodule DrivewayOS.Repo.Migrations.AddAppointmentAcquisitionChannel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :acquisition_channel, :text
    end
  end

  def down do
    alter table(:appointments) do
      remove :acquisition_channel
    end
  end
end
