defmodule DrivewayOS.Repo.Migrations.AddPlanTierToTenant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :plan_tier, :text
    end
  end

  def down do
    alter table(:tenants) do
      remove :plan_tier
    end
  end
end
