defmodule DrivewayOS.Repo.Migrations.AddAdditionalVehiclesToAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :additional_vehicles, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:appointments) do
      remove :additional_vehicles
    end
  end
end
