defmodule DrivewayOS.Repo.Migrations.AddAppointmentReminderSentAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :reminder_sent_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:appointments) do
      remove :reminder_sent_at
    end
  end
end
