defmodule DrivewayOS.Repo.Migrations.AddCustomerMarketingOptOut do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :marketing_emails_ok?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:customers) do
      remove :marketing_emails_ok?
    end
  end
end
