defmodule DrivewayOS.Repo.Migrations.Slice6aAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :scheduled_at, :utc_datetime, null: false
      add :duration_minutes, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :price_cents, :bigint, null: false
      add :vehicle_description, :text, null: false
      add :service_address, :text, null: false
      add :notes, :text
      add :cancellation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "appointments_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "appointments_service_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointments, "appointments_customer_id_fkey")

    drop constraint(:appointments, "appointments_service_type_id_fkey")

    drop table(:appointments)
  end
end
