defmodule DrivewayOS.Repo.Migrations.AddLoyaltyColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :loyalty_threshold, :bigint
    end

    alter table(:customers) do
      add :loyalty_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:customers) do
      remove :loyalty_count
    end

    alter table(:tenants) do
      remove :loyalty_threshold
    end
  end
end
